[versions]
spring-boot-version = "4.0.0"
spring-dependency-management = "1.1.7"
lombok = "1.18.34"
junit-platform = "1.10.2"
sonarlint = "7.0.0-rc-4"
freefair-aggregate-jacoco = "9.0.0"
palantir = "6.66.0"
springdoc-openapi-version = "2.8.14"

[libraries]
spring-boot-micrometer-tracing = { module = "org.springframework.boot:spring-boot-micrometer-tracing"}
spring-boot-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator"}
spring-boot-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc"}
spring-boot-restclient = { module = "org.springframework.boot:spring-boot-starter-restclient"}
spring-boot-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-security-oauth2-client"}
spring-boot-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-security-oauth2-resource-server"}
spring-boot-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc"}
micrometer-bridge-brave = { module = "io.micrometer:micrometer-tracing-bridge-brave" }
spring-cloud-starter = { module = "org.springframework.cloud:spring-cloud-starter"}
spring-cloud-resilience4j = { module = "org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j" }


springdoc-openapi-web-mvc = { module = "org.springdoc:springdoc-openapi-starter-webmvc-api", version.ref = "springdoc-openapi-version" }


lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
h2 = { module = "com.h2database:h2" }

spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor"}

spring-boot-micrometer-tracing-test = { module = "org.springframework.boot:spring-boot-micrometer-tracing-test"}
spring-boot-jdbc-test = { module = "org.springframework.boot:spring-boot-starter-jdbc-test"}
spring-boot-restclient-test = { module = "org.springframework.boot:spring-boot-starter-restclient-test"}
spring-boot-oauth2-client-test = { module = "org.springframework.boot:spring-boot-starter-security-oauth2-client-test"}
spring-boot-oauth2-resource-server-test = { module = "org.springframework.boot:spring-boot-starter-security-oauth2-resource-server-test"}
spring-boot-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test"}
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }




# plugins library
spring-boot-plugin= { module ="org.springframework.boot:org.springframework.boot.gradle.plugin" ,version.ref = "spring-boot-version" }
spring-dependency-plugin= { module ="io.spring.dependency-management:io.spring.dependency-management.gradle.plugin" ,version.ref ="spring-dependency-management" }
sonarlint-plugin= { module = "name.remal.sonarlint:name.remal.sonarlint.gradle.plugin", version.ref = "sonarlint" }
freefair-aggregate-jacoco-plugin = { module = "io.freefair.aggregate-jacoco-report:io.freefair.aggregate-jacoco-report.gradle.plugin", version.ref = "freefair-aggregate-jacoco" }
palantir-checkstyle-plugin = { module = "com.palantir.baseline-checkstyle:com.palantir.baseline-checkstyle.gradle.plugin" , version.ref="palantir"}
palantir-idea-plugin = { module = "com.palantir.baseline-checkstyle:com.palantir.baseline-checkstyle.gradle.plugin" , version.ref="palantir"}
graalVm-plugin = { module = "org.graalvm.buildtools:native-gradle-plugin" , version="0.11.3"}

[bundles]
core-spring-boot = [
    "spring-boot-micrometer-tracing",
    "spring-boot-actuator",
    "spring-boot-jdbc",
    "spring-boot-restclient",
    "spring-boot-webmvc",
    "micrometer-bridge-brave",
    "spring-cloud-starter",
    "spring-cloud-resilience4j",
    "springdoc-openapi-web-mvc"
]
core-testing = [
    "spring-boot-micrometer-tracing-test",
    "spring-boot-jdbc-test",
    "spring-boot-restclient-test",
    "spring-boot-webmvc-test",
    "junit-platform-launcher"
]

[plugins]
spring-boot = { id = "org.springframework.boot" , version.ref = "spring-boot-version"}
spring-dependency = { id ="io.spring.dependency-management" , version.ref ="spring-dependency-management" }